window.TH_FR=window.TH_FR||{};Object.assign(window.TH_FR,{
'41':`<p>Le silence est une omission du temps. Là où il n’y a pas de son, il ne reste que le temps pur, indivisible. Là où il n’y a pas de son, il ne reste que nous. Nous nous rencontrons nous-mêmes et devenons le contenu du temps.</p><p>Un vide, une pause, est un territoire de liberté. À travers lui, le monde intérieur d’une personne fait irruption. Il ne peut être contrôlé de l’extérieur et constitue donc une menace pour le monde extérieur.</p><p>Chaque compositeur compose non seulement des sons, mais aussi du silence. Le silence n’existe pas ; il faut donc le recomposer chaque fois. Il peut être aussi individuel qu’une mélodie, un rythme, une harmonie ou une forme.</p>`,
'42':`<p>La musique est du temps entendu. La mémoire abolit le temps linéaire : les événements restent simultanément présents, comme des objets dans l’espace. Peut-être le temps n’est-il qu’un attribut de la perception — conséquence de notre incapacité à embrasser la simultanéité, l’éternel présent.</p>`,
'43':`<p>Au moment où je dis « je sais », je ferme la possibilité de savoir.</p>`,
'44':`<p>Un quatuor à cordes n’est pas seulement quatre instruments : ce sont quatre personnes vivantes sur scène, beaucoup plus de personnes dans la salle, et même celles qui n’ont pas réussi à y entrer. Tout cela aussi est un quatuor à cordes.</p>`,
'45':`<p>Il n’y a pas de musique. Il existe peut-être une somme toujours croissante d’idées sur ce qu’est la musique. Faire de la musique signifie donc avoir affaire à quelque chose qui n’existe pas — à l’inconnu.</p><p>La musique nous donne la possibilité de rencontrer l’inconnu, de l’habiter, de nous y reconnaître et, finalement, de l’accepter. La peur de l’inconnu nourrit les guerres.</p>`,
'46':`<p>Mon guilty pleasure est l’ambient dub. J’y vois une étude du déplacement de l’accent, de l’événement vers l’espace dans lequel il existe — vers les propriétés de cet espace.</p><p>Autre caractéristique : la disproportion entre l’événement minimal — presque un non-événement — et sa résonance, souvent massive et stratifiée. L’événement est nécessaire pour révéler l’espace, comme la lumière est nécessaire pour voir dans l’obscurité.</p><p>Le « beat », la répétition, m’intéresse ici non comme fonction dansante, mais comme propriété de l’objet — sa présence discrète et durable, comme une étoile qui scintille.</p><p>Enfin, l’auditeur se retrouve quelque part entre l’objet lointain — en voie de disparition — et l’espace qui s’élargit. Pas de fétichisation des propriétés de l’objet, du métier, de l’auteur.</p><p>Un lien (in)direct avec Lucier, certainement.</p>`,
'47':`<p>Je vois le doute comme l’une des principales forces motrices de la connaissance et, par conséquent, de la création. En nous demandant « que suis-je ? », nous nous confrontons à l’éternelle question « être ou ne pas être » — nous définissons notre position par rapport à ce que nous nous autorisons à reconnaître comme partie de nous-mêmes et à ce que nous refusons de reconnaître ainsi.</p><p>Je ne vois qu’une seule réponse possible à cette question : douter. Il ne s’agit pas d’un choix — c’est une question rhétorique. Quelque part entre « être » et « ne pas être » se trouve le « je » qui doute.</p>`,
'48':`<p>Le non-être est l’un des états de l’être. « Être » et « ne pas être » sont comme inspirer et expirer — et peu importe réellement lequel est lequel ; ils sont simultanément l’un et l’autre, se conditionnent mutuellement et dessinent le champ de nos luttes existentielles et créatrices.</p><p>Autrement dit, « être » et « ne pas être » sont « je » et « je ». Pourtant, entre l’inspiration et l’expiration, entre moi et moi, il existe un espace qui sépare l’un de l’autre et constitue en même temps quelque chose de troisième : une mystérieuse virgule — la différence entre l’un et le même.</p><p>C’est précisément cette différence qui est le doute.</p>`,
'49':`<p>La nécessité d’un acte créateur naît du doute, du sentiment que ce qui existe est insuffisant — ou, plus précisément, qu’il ne s’est pas entièrement révélé. Ce n’est ni une déception face à ce qui existe ni son rejet. C’est un doute créateur.</p>`,
'50':`<p>Le doute élargit la connaissance. Chaque nouveau texte — y compris musical — est une fissure dans la somme a priori des textes, une certaine potentialité de textes qui existe indépendamment de notre volonté. À travers de telles fissures, nous apprenons à connaître cette somme, comme les scientifiques découvrent les propriétés de la matière à travers un minuscule échantillon sous un microscope.</p><p>Une nouvelle composition ne s’ajoute pas à cette somme — elle élargit notre compréhension de celle-ci. Elle est déjà contenue en elle.</p>`,
'51':`<p>Le monde autoréférentiel, autopoïétique, qui se révèle devant nous — en nous — avec ses connexions communicatives fermées, ne nie pas la possibilité de l’autre : un autre qui existe, pense, connaît et crée en parallèle — non dans un dialogue, mais dans un dilogue, un polylogue — une somme de monologues qui se déploient chacun dans sa propre dimension.</p><p>Ainsi, l’autre se manifeste par son absence. Comme dans un jardin de pierres japonais, disposé de telle sorte que, de chaque point de vue, l’une des pierres soit cachée par les autres. C’est précisément cette pierre « absente » qui devient le but et le contenu de l’art de composer le jardin.</p>`,
'52':`<p>Si le moteur de la création est le doute, alors les nouvelles technologies, et en particulier l’intelligence artificielle, ne représentent aucun danger pour le créateur. Le danger apparaît lorsque les résultats des opérations d’un algorithme sont acceptés comme une vérité absolue. Mais cela ne concerne pas seulement l’IA. Les modèles historiques, les systèmes musicaux, les écoles, la technologie et notre propre expérience peuvent se substituer à la pensée tout aussi efficacement qu’un algorithme — parce que nous avons pris l’habitude de leur faire confiance.</p><p>En ce sens, l’IA se trouve dans une position assez étrange : on ne peut pas lui faire entièrement confiance, et nous le savons — elle hallucine. La connaissance est précisément la plus dangereuse lorsqu’elle cesse de soupçonner la possibilité de sa propre hallucination et commence à se présenter comme absolue.</p><p>Si, en revanche, la tâche première de l’auteur est de problématiser, l’IA ne prend pas la place de l’auteur. La place de l’auteur émerge précisément dans la relation entre la proposition de la machine et la méfiance envers cette proposition.</p>`
});